# Generated by Django 3.0.4 on 2020-08-10 13:31

import data_storage.enums.brain_subzone
import data_storage.enums.brain_zone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrainQuantification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ki_pos', models.IntegerField(blank=True, null=True)),
                ('ki_min', models.IntegerField(blank=True, null=True)),
                ('zone', models.CharField(choices=[(data_storage.enums.brain_zone.BrainZone['Cortex'], 'Cortex'), (data_storage.enums.brain_zone.BrainZone['POA'], 'POA'), (data_storage.enums.brain_zone.BrainZone['Striatum'], 'Striatum'), (data_storage.enums.brain_zone.BrainZone['Hippocampus'], 'Hippocampus'), (data_storage.enums.brain_zone.BrainZone['Triangulo'], 'Triangulo'), (data_storage.enums.brain_zone.BrainZone['DG'], 'DG')], max_length=12)),
                ('sub_zone', models.CharField(choices=[(data_storage.enums.brain_subzone.BrainSubZone['Empty'], None), (data_storage.enums.brain_subzone.BrainSubZone['MZ'], 'MZ'), (data_storage.enums.brain_subzone.BrainSubZone['II_III'], 'II_III'), (data_storage.enums.brain_subzone.BrainSubZone['IV'], 'IV'), (data_storage.enums.brain_subzone.BrainSubZone['V'], 'V'), (data_storage.enums.brain_subzone.BrainSubZone['VI'], 'VI')], max_length=12)),
                ('Area', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
