# Generated by Django 3.0.4 on 2020-08-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brainquantification',
            old_name='ki_min',
            new_name='ki_neg',
        ),
        migrations.AlterField(
            model_name='brainquantification',
            name='sub_zone',
            field=models.CharField(choices=[(None, 'Empty'), ('MZ', 'MZ'), ('II_III', 'II_III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI')], max_length=12),
        ),
        migrations.AlterField(
            model_name='brainquantification',
            name='zone',
            field=models.CharField(choices=[('Cortex', 'Cortex'), ('POA', 'POA'), ('Striatum', 'Striatum'), ('Hippocampus', 'Hippocampus'), ('Triangulo', 'Triangulo'), ('DG', 'DG')], max_length=12),
        ),
    ]
