# Generated by Django 3.0.4 on 2020-08-10 13:54

import data_storage.enums.brain_subzone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0002_auto_20200810_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainQuantificationImport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('csv_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='brainquantification',
            name='sub_zone',
            field=models.CharField(choices=[('Empty', 'Empty'), ('MZ', 'MZ'), ('II_III', 'II_III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI')], default=data_storage.enums.brain_subzone.BrainSubZone['Empty'], max_length=12),
        ),
    ]
