# Generated by Django 3.0.4 on 2020-08-10 14:51

import data_storage.enums.brain_subzone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0004_auto_20200810_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brainquantification',
            name='Area',
        ),
        migrations.AddField(
            model_name='brainquantification',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brainquantification',
            name='brain_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='brainquantification',
            name='slice_thickness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brainquantification',
            name='stage',
            field=models.CharField(choices=[('E12.5', 'E12_5'), ('E14.5', 'E14_5'), ('E16.5', 'E16_5'), ('E18.5', 'E18_5'), ('P0', 'P0'), ('P3', 'P3'), ('P5', 'P5'), ('P6', 'P6'), ('P7', 'P7'), ('P9', 'P9'), ('P14', 'P14'), ('P20', 'P20'), ('P60', 'P60')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brainquantificationimport',
            name='slice_thickness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brainquantificationimport',
            name='stage',
            field=models.CharField(choices=[('E12.5', 'E12_5'), ('E14.5', 'E14_5'), ('E16.5', 'E16_5'), ('E18.5', 'E18_5'), ('P0', 'P0'), ('P3', 'P3'), ('P5', 'P5'), ('P6', 'P6'), ('P7', 'P7'), ('P9', 'P9'), ('P14', 'P14'), ('P20', 'P20'), ('P60', 'P60')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brainquantificationimport',
            name='sub_zone',
            field=models.CharField(choices=[('Empty', 'Empty'), ('MZ', 'MZ'), ('II_III', 'II_III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI')], default=data_storage.enums.brain_subzone.BrainSubZone['Empty'], max_length=12),
        ),
        migrations.AddField(
            model_name='brainquantificationimport',
            name='zone',
            field=models.CharField(choices=[('Cortex', 'Cortex'), ('POA', 'POA'), ('Striatum', 'Striatum'), ('Hippocampus', 'Hippocampus'), ('Triangulo', 'Triangulo'), ('DG', 'DG')], default='', max_length=12),
            preserve_default=False,
        ),
    ]
