# Generated by Django 3.0.4 on 2020-08-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0005_auto_20200810_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainquantification',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
