# Generated by Django 3.0.4 on 2020-08-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0006_brainquantification_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainquantification',
            name='percent_ki_67',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
