# Generated by Django 3.0.4 on 2020-08-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0007_brainquantification_percent_ki_67'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainquantification',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brainquantification',
            name='density_ki67',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
