# Generated by Django 3.0.4 on 2020-08-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0008_auto_20200810_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brainquantificationimport',
            name='sub_zone',
        ),
    ]
