# Generated by Django 3.0.4 on 2020-08-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0010_auto_20200822_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainquantificationimport',
            name='slice_thickness',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
    ]
