# Generated by Django 3.0.4 on 2020-08-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0011_auto_20200822_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainquantification',
            name='ki_neg_updated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brainquantification',
            name='ki_pos_updated',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
