# Generated by Django 3.0.4 on 2020-08-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0012_auto_20200822_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainquantification',
            name='ki_neg_updated',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brainquantification',
            name='ki_pos_updated',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brainquantification',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
