# Generated by Django 3.1 on 2020-09-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0014_brainquantification_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainquantification',
            name='area_measure',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
